export const challengeLogEntries = [
  {
    id: "ansan-contest",
    result: "붙음",
    activity: "안산공모전",
    project: "안산 골목 회복 신호등",
    repository: {
      name: "inhodev/ansan-life-map",
      url: "https://github.com/inhodev/ansan-life-map",
      visibility: "PRIVATE",
    },
  },
  {
    id: "codex-student-hackathon",
    result: "붙음",
    activity: "코덱스 스튜던트 해커톤",
    project: "MeSource",
    projectNote: "개인 메모를 모아 검색하고 서로 연결해 주는 AI 지식 관리 도구입니다.",
    repository: {
      name: "codex-hakathon-1/personal-rag-ontology",
      url: "https://github.com/codex-hakathon-1/personal-rag-ontology",
      visibility: "PUBLIC",
    },
  },
  {
    id: "codex-global-feedback",
    result: "붙음",
    activity: "코덱스 글로벌 피드백 세션",
    connection: "참여 이력 · 연결 프로젝트 없음",
    project: null,
    repository: null,
  },
  {
    id: "ajou-inha-hackathon",
    result: "붙음",
    activity: "아주·인하 해커톤",
    project: "Aington",
    repository: {
      name: "inhodev/Aington",
      url: "https://github.com/inhodev/Aington",
      visibility: "PUBLIC",
    },
  },
  {
    id: "asan-doers",
    result: "떨어짐",
    activity: "아산 두어스",
    project: "Copyvara",
    repository: {
      name: "inhodev/copyvara-fast",
      url: "https://github.com/inhodev/copyvara-fast",
      visibility: "PUBLIC",
    },
  },
  {
    id: "u300",
    result: "떨어짐",
    activity: "U300",
    project: "Copyvara",
    repository: {
      name: "inhodev/copyvara-fast",
      url: "https://github.com/inhodev/copyvara-fast",
      visibility: "PUBLIC",
    },
  },
  {
    id: "alab-accelerating",
    result: "떨어짐",
    activity: "아랩 엑셀러레이팅",
    project: "Copyvara",
    repository: {
      name: "inhodev/copyvara-fast",
      url: "https://github.com/inhodev/copyvara-fast",
      visibility: "PUBLIC",
    },
  },
  {
    id: "mock-startup-round-two",
    result: "떨어짐",
    activity: "모창 2라운드",
    project: "RunQuest",
    projectNote: "달린 거리와 속도에 맞춰 이야기가 이어지는 오디오 러닝 앱입니다.",
    repository: {
      name: "inhodev/RunQuest",
      url: "https://github.com/inhodev/RunQuest",
      visibility: "PRIVATE",
    },
  },
  {
    id: "codex-game-hackathon",
    result: "떨어짐",
    activity: "코덱스 게임 해커톤",
    project: "Tiny Airport",
    projectNote: "공항에서 비행기를 착륙시키고 이동시킨 뒤, 출발 준비와 이륙까지 운영하는 PC 웹게임입니다.",
    repository: {
      name: "inhodev/tiny-airport",
      url: "https://github.com/inhodev/tiny-airport",
      visibility: "PRIVATE",
    },
  },
  {
    id: "incheon-university-academy",
    result: "떨어짐",
    activity: "인천대학연합아카데미",
    project: "imfine / 프로젝트 타임슬립",
    projectNote: "과거 시장 상황을 보고 투자 결정을 연습하는 게임입니다. 실제 계좌와는 연결되지 않습니다.",
    repository: {
      name: "inhodev/imfine",
      url: "https://github.com/inhodev/imfine",
      visibility: "PRIVATE",
    },
  },
  {
    id: "jocoding-hackathon",
    result: "떨어짐",
    activity: "조코딩 해커톤",
    project: "Copyvara",
    repository: {
      name: "inhodev/copyvara-fast",
      url: "https://github.com/inhodev/copyvara-fast",
      visibility: "PUBLIC",
    },
  },
];
